# Generated by Django 4.2.9 on 2024-02-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
